# The language of this repository
language:
    - C

# Only test the master branch
branches:
    only:
        - master

# Indicate to the Makefiles to always use an ARM cross compiler
env:
    global:
        - ARCH=arm
        - CROSS_COMPILE=arm-linux-gnueabihf-

# Install the needed build tools before testing and installing any dependencies
# (e.g. ARM cross compiler)
before_install:
    - sudo apt-get update
    - sudo apt-get install -y git
    - sudo apt-get install -y gcc-arm-linux-gnueabihf
    - sudo apt-get install -y u-boot-tools

# Clone and build the mainline Xilinx Kernel (4.x) the driver is built against.
install:
    - git clone --depth 1 https://github.com/Xilinx/linux-xlnx xilinx_linux
    - cd xilinx_linux
    - make xilinx_zynq_defconfig
    - make -j 8 UIMAGE_LOADADDR=0x8000 uImage
    - cd ..

# Build the driver against the kernels to verify that it compiles properly
script:
    - make KBUILD_DIR=xilinx_linux
    - make KBUILD_DIR=xilinx_linux clean
